version: '2.0'
services:      
  db:
    image: mariadb:10.1
    container_name: seafile-mysql
    restart: always
    environment_file:
      - secret.env
    volumes:
      - ./cloud/db:/var/lib/mysql
    networks:
      - seafile-net

  memcached:
    image: memcached:1.5.6
    container_name: seafile-memcached
    entrypoint: memcached -m 256
    restart: always
    networks:
      - seafile-net

  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
    restart: always
    volumes:
      - ./cloud/data:/shared
    environment_file:
      - secret.env
    environment:
      - TIME_ZONE=Europe/Moscow
      - SEAFILE_SERVER_LETSENCRYPT=false
      - SEAFILE_SERVER_HOSTNAME=cloud.awoo.moe
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cloud.rule=Host(`cloud.awoo.moe`)"
      - "traefik.http.routers.cloud.tls=true"
      - "traefik.http.routers.cloud.tls.certresolver=le"
    depends_on:
      - db
      - memcached
    networks:
      - internal
      - seafile-net

networks:
  seafile-net:
  internal:
    external: true
