version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./awoo/:/data/www/awoo/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`awoo.moe`)"
      - "traefik.http.routers.nginx.tls=true"  
      - "traefik.http.routers.nginx.tls.certresolver=le"
    networks:
      - internal

networks:
  internal:
    external: true
