version: "3.3"

services:
  traefik:
    image: traefik
    container_name: traefik
    command:
      - --api.dashboard=true
      - --entrypoints.websecure.address=:443
      - --providers.docker
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=internal
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --certificatesresolvers.le.acme.email=yiffmewithyour@cock.li
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.awoo.moe`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=le"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$bMpfZvIc$$gPQ6p8CbZOlRJrQb2VeVh/"
    ports:
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs/:/letsencrypt/
    networks:
      - internal
    restart: always

networks:
  internal:
    external: true
